name: pytest
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
    pull_request:
      branches:
        - master
jobs:
  run:
    name: Run unit tests with codecov upload
    runs-on: ${{ matrix.os }}
    env:
      USING_COVERAGE: '3.7'
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7]
    steps:
    - uses: actions/checkout@master

    # https://github.com/actions/virtual-environments/issues/294
    - name: Configure path to rc.exe for Python 3.5
    run: |
      function Invoke-VSDevEnvironment {
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $installationPath = & $vswhere -prerelease -legacy -latest -property installationPath
          $Command = Join-Path $installationPath "Common7\Tools\vsdevcmd.bat"
              & "${env:COMSPEC}" /s /c "`"$Command`" -no_logo && set" | Foreach-Object {
              if ($_ -match '^([^=]+)=(.*)') {
                  [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2])
              }
          }
      }
      Invoke-VSDevEnvironment
      Get-Command rc.exe | Format-Table -AutoSize
    if: matrix.os == 'windows-latest' && matrix.python-version == '3.5'

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Static code checking with pyflakes
      run: |
        pip3 install pyflakes
        pyflakes mkdocs_enumerate_headings_plugin
    - name: Run unit tests
      run: |
        pip3 install --upgrade pip
        pip3 install -r tests/test_requirements.txt
        pip3 install -e .
        pytest --cov=mkdocs_enumerate_headings_plugin --cov-report=xml -vvv
    - name: Upload coverage to Codecov
      if: "contains(env.USING_COVERAGE, matrix.python-version)"
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true